repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Linter
      - id: ruff
        args: ["--fix", "--ignore=E501,E402,W293"]
        exclude: "^third_party/"
      # Formatter
      - id: ruff-format
        exclude: "^third_party/"
